---
- name: Manage DNS Zone and Packages Using Ansible
  hosts: all  # Assuming 'all' group includes ipaserver and other nodes

  tasks:
    - name: Install FreeIPA server packages on ipaserver
      when: inventory_hostname in groups['ipaserver']
      ansible.builtin.yum:
        name:
          - ipa-server
          - ipa-server-dns
          - ipa-server-trust-ad
        state: present
      become: true

    - name: Install FreeIPA client and OpenLDAP clients on other nodes
      when: inventory_hostname not in groups['ipaserver']
      ansible.builtin.yum:
        name:
          - ipa-client
          - openldap-clients
        state: present
      become: true

    - name: Create DNS zone if it doesn't exist
      community.general.ipa_dnszone:
        name: "{{ dns_zone }}"
        state: present
      vars:
        dns_zone: example.com  # Specify your DNS zone

    - name: Loop through host groups and add DNS records
      ansible.builtin.include_tasks: add_dns_records.yml
      loop:
        - group_name: base-master
        - group_name: base-workers
        - group_name: acs-master
        - group_name: acs-workers
      loop_control:
        loop_var: group_info
      vars:
        dns_zone: example.com  # Specify your DNS zone

