---
- name: Setup environment
  hosts: all
  become: yes
  tasks:
    - name: Set static hostname
      hostname:
        name: "{{ inventory_hostname }}"
        static: yes

    - name: Update /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      with_items:
        - "127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4"
        - "::1 localhost localhost.localdomain localhost6 localhost6.localdomain6"
        - "172.31.24.240 ipaserver.cdppvcds.com ipaserver"
        - "172.31.27.139 cldr-mngr.cdppvcds.com cldr-mngr"
        - "172.31.21.104 pvcbase-master.cdppvcds.com pvcbase-master"
        # Add other host entries here

    - name: Update /etc/resolv.conf
      template:
        src: resolv.conf.j2
        dest: /etc/resolv.conf

    - name: Disable SELinux
      selinux:
        state: disabled

    - name: Configure transparent hugepages
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        sysctl_set: yes
      with_items:
        - { name: "vm.nr_hugepages", value: 0 }
        - { name: "vm.hugetlb_shm_group", value: 0 }

    - name: Install Python 3.9
      raw: |
        dnf -y update
        dnf -y groupinstall "Development Tools"
        dnf -y install epel-release openssl-devel bzip2-devel libffi-devel xz-devel wget
        wget https://www.python.org/ftp/python/3.9.18/Python-3.9.18.tgz
        tar xvf Python-3.9.18.tgz
        cd Python-3.9.18
        ./configure --enable-optimizations
        make altinstall

    - name: Install psycopg2-binary
      pip:
        name: psycopg2-binary
        state: present

    - name: Disable firewalld
      service:
        name: firewalld
        state: stopped
        enabled: no

    - name: Disable IPv6
      sysctl:
        name: net.ipv6.conf.all.disable_ipv6
        value: 1
        sysctl_set: yes
        reload: yes

