postgresql_packages:
  - postgresql-server
  - postgresql-contrib

postgresql_config_path: "/var/lib/pgsql/data"
postgresql_ssl_cert_path: "/var/lib/pgsql/data"

cloudera_db_name: "scm"
cloudera_db_user: "scm"
cloudera_db_password: "Cloudera@123"
