
CREATE ROLE scm LOGIN PASSWORD 'scm';
CREATE DATABASE scm OWNER scm ENCODING 'UTF8';
GRANT ALL PRIVILEGES ON DATABASE scm TO scm;

CREATE ROLE rman LOGIN PASSWORD 'rman';
CREATE DATABASE rman OWNER rman ENCODING 'UTF8';
GRANT ALL PRIVILEGES ON DATABASE rman TO rman;

CREATE ROLE hue LOGIN PASSWORD 'hue';
CREATE DATABASE hue OWNER hue ENCODING 'UTF8';
GRANT ALL PRIVILEGES ON DATABASE hue TO hue;

CREATE ROLE hive LOGIN PASSWORD 'hive';
CREATE DATABASE hive OWNER hive ENCODING 'UTF8';
GRANT ALL PRIVILEGES ON DATABASE hive TO hive;

CREATE ROLE oozie LOGIN PASSWORD 'oozie';
CREATE DATABASE oozie OWNER oozie ENCODING 'UTF8';
GRANT ALL PRIVILEGES ON DATABASE oozie TO oozie;

CREATE ROLE rangeradmin LOGIN PASSWORD 'rangeradmin';
CREATE DATABASE ranger OWNER rangeradmin ENCODING 'UTF8';
GRANT ALL PRIVILEGES ON DATABASE ranger TO rangeradmin;

-- For Ranger KMS, use rangerkms rather than rangeradmin user.
CREATE ROLE rangerkms LOGIN PASSWORD 'rangerkms';
CREATE DATABASE rangerkms OWNER rangerkms ENCODING 'UTF8';
GRANT ALL PRIVILEGES ON DATABASE rangerkms TO rangerkms;

CREATE ROLE schemaregistry LOGIN PASSWORD 'schemaregistry';
CREATE DATABASE schemaregistry OWNER schemaregistry ENCODING 'UTF8';
GRANT ALL PRIVILEGES ON DATABASE schemaregistry TO schemaregistry;

CREATE ROLE yqm LOGIN PASSWORD 'yqm';
CREATE DATABASE yqm OWNER yqm ENCODING 'UTF8';
GRANT ALL PRIVILEGES ON DATABASE yqm TO yqm;

-- For the SMM metadata store, create a database called smm with the password smm:
CREATE ROLE smm LOGIN PASSWORD 'smm';
CREATE DATABASE smm OWNER smm ENCODING 'UTF8';
GRANT ALL PRIVILEGES ON DATABASE smm TO smm;

CREATE ROLE das LOGIN PASSWORD 'das';
CREATE DATABASE das OWNER das ENCODING 'UTF8';
GRANT ALL PRIVILEGES ON DATABASE das TO das;

ALTER DATABASE hive SET standard_conforming_strings=off;
ALTER DATABASE oozie SET standard_conforming_strings=off;

SELECT 1;

SHOW ssl;