- name: Copy PostgreSQL configuration file
  template:
    src: postgresql.conf.j2
    dest: "{{ postgresql_config_path }}/postgresql.conf"
    owner: postgres
    group: postgres
    mode: "0644"
  notify: Restart PostgreSQL

- name: Configure pg_hba.conf for SSL authentication
  template:
    src: pg_hba.conf.j2
    dest: "{{ postgresql_config_path }}/pg_hba.conf"
    owner: postgres
    group: postgres
    mode: "0644"
  notify: Restart PostgreSQL
