- name: Set Cloudera Manager Host IP
  ansible.builtin.set_fact:
    cm_host: "{{ hostvars[groups['cldr-mngr'][0]].ansible_host }}" # Fetch IP of the first host in cldr-mngr group

- name: Debug cm_host
  ansible.builtin.debug:
    msg: "cm_host is set to {{ cm_host }}"

- name: Get Cloudera Manager API version
  ansible.builtin.uri:
    url: http://{{ cm_host }}:{{ cm_port }}/api/version
    method: GET
    status_code: [200, 301, 303]
    user: "{{ cm_admin_user }}"
    password: "{{ cm_admin_pass }}"
    force_basic_auth: yes
    return_content: yes
    validate_certs: no
  register: result

- name: Set base CM API URL
  ansible.builtin.set_fact:
    cm_api_url: "http://{{ cm_host }}:{{ cm_port }}/api/{{ result.content }}"

- name: Print cm_api_url
  ansible.builtin.debug:
    msg: "cm_api_url is set to {{ cm_api_url }}"
