---
- name: Playbook to configure IPA servers
  hosts: ipaserver
  become: true
#  vars_files:
#  - playbook_sensitive_data.yml

  roles:
  - role: ipaserver
    state: present

---
- name: Playbook to configure IPA clients with username/password
  hosts: ipaclients
  become: true

  roles:
  - role: ipaclient
    state: present

