---
- name: Install Nginx
  yum:
    name: nginx
    state: present

- name: Configure Nginx for Private Repo
  template:
    src: nginx.repo.j2
    dest: /etc/nginx/conf.d/private-repo.conf

- name: Start Nginx
  service:
    name: nginx
    state: started
    enabled: yes
