### ansible-playbook -i inventory.ini 10_setup_internal_repo.yml
---
- name: Set up HTTPD to host Red Hat repository
  hosts: cldr-mngr
  become: true

  tasks:
    - name: Install required packages
      dnf:
        name:
          - httpd
          - mod_ssl
          - createrepo_c
        state: present

    - name: Generate CA certificate using OpenSSL
      command: openssl req -newkey rsa:2048 -nodes -keyout /etc/pki/tls/private/httpd.key -x509 -days "{{ cert_days_valid }}" -out /etc/pki/tls/certs/httpd.crt -subj "{{ cert_subj }}"
      args:
        creates: /etc/pki/tls/private/httpd.key

    - name: Create directory for HTTPS content
      file:
        path: "{{ httpd_repo_dir }}"
        state: directory
        mode: '0755'

    - name: Add secure content to the HTTPS directory
      copy:
        content: "secure content"
        dest: "{{ httpd_repo_dir }}/index.html"
        mode: '0644'

    - name: Configure the server name in httpd.conf
      lineinfile:
        path: "{{ httpd_conf_file }}"
        regexp: '^#ServerName'
        line: "ServerName {{ server_name }}:80"
        create: yes

    - name: Start and enable HTTPD service
      systemd:
        name: httpd
        state: started
        enabled: yes

    - name: Verify httpd service is enabled
      systemd:
        name: httpd
        enabled: yes