### ansible-playbook -i inventory.ini 3_setup_autossh.yml
- name: Generate and Distribute SSH Key Pair
  hosts: ipaserver
  become: true
  # vars_files:
  #   - ssh_vars.yml

  tasks:
    - name: Ensure .ssh directory exists for user
      file:
        path: "{{ ssh_dir }}"
        state: directory
        mode: "0700"
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"

    - name: Check if SSH private key exists
      stat:
        path: "{{ private_key_path }}"
      register: private_key_stat

    - name: Generate SSH key pair
      openssh_keypair:
        path: "{{ private_key_path }}"
        type: rsa
        size: 2048
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"
        mode: "0600"
      when: not private_key_stat.stat.exists or force_generate | bool

    - name: Read the public key file
      slurp:
        src: "{{ public_key_path }}"
      register: public_key_data

    - name: Ensure public key is available
      fail:
        msg: "Failed to read public key from {{ public_key_path }}"
      when: public_key_data is not defined or public_key_data.content is not defined

    - name: Add public key to authorized_keys
      authorized_key:
        user: "{{ ssh_user }}"
        state: present
        key: "{{ public_key_data.content | b64decode }}"
      when: public_key_data.content is defined

- name: Copy SSH Key to Other Hosts
  hosts: all:!ipaserver
  become: true
  # vars_files:
  #   - ssh_vars.yml

  tasks:
    - name: Ensure .ssh directory exists on target hosts
      file:
        path: "{{ ssh_dir }}"
        state: directory
        mode: "0700"
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"

    - name: Copy SSH private key to other hosts
      copy:
        src: "{{ private_key_path }}"
        dest: "{{ private_key_path }}"
        mode: "0600"
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"

    - name: Copy SSH public key to other hosts
      copy:
        src: "{{ public_key_path }}"
        dest: "{{ public_key_path }}"
        mode: "0644"
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"

    - name: Copy authorized_keys file to other hosts
      copy:
        src: "{{ authorized_keys_path }}"
        dest: "{{ authorized_keys_path }}"
        mode: "0600"
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"
