### ansible-playbook -i inventory.ini 5_prereq_setup.yml
---
- name: System Update and Package Installation
  hosts: all
  become: yes  # Ensure you have the necessary privileges
  tasks:

    # - name: Update all packages
    #   dnf:
    #     name: "*"
    #     state: latest
    #   register: update_result

    - name: Install required packages
      dnf:
        name:
          - wget
          - telnet
          - net-tools
          - bind-utils
          - iproute
          - traceroute
          - nc
          - python3
          - python3-pip
          - gcc  # Required for compiling some Python packages
          - python3-devel  # Required for some Python libraries
          - postgresql-libs  # Ensures PostgreSQL dependencies are installed
        state: present

    - name: Upgrade pip3 to the latest version
      pip:
        name: pip
        state: latest
        executable: pip3
      become: yes
    
    - name: Verify if Python3 is installed
      command: python3 --version
      register: python_version
      ignore_errors: yes

    - name: Print Python3 version
      debug:
        msg: "Python3 version: {{ python_version.stdout }}"
      when: python_version.rc == 0

    - name: Verify if Pip3 is installed
      command: pip3 --version
      register: pip_version
      ignore_errors: yes

    - name: Print Pip3 version
      debug:
        msg: "Pip3 version: {{ pip_version.stdout }}"
      when: pip_version.rc == 0

    - name: Ensure Python3 and Pip3 are installed
      package:
        name: 
          - python3
          - python3-pip
        state: present

    - name: Install psycopg2-binary
      pip:
        name: psycopg2-binary
        state: present
        executable: pip3
      become: yes
