---
- name: Install the ansible.posix collection using ansible-galaxy
  hosts: localhost
  become: yes
  tasks:
    # Task to install the ansible.posix collection using ansible-galaxy
    - name: Install ansible.posix collection
      ansible.builtin.command:
        cmd: ansible-galaxy collection install ansible.posix
      become: yes
      changed_when: false
      failed_when: false           

- name: Set SELinux to permissive and ensure persistence across reboots
  hosts: 'all:!ipaserver'
  become: yes
  tasks:

    - name: Verify current SELinux status before change
      command: sestatus
      register: selinux_status_before
      changed_when: false
      failed_when: false

    - name: Print SELinux status before change
      debug:
        msg: "Before change, SELinux status: {{ selinux_status_before.stdout }}"

    - name: Set SELinux to permissive mode immediately
      command: setenforce 0
      when: "'Permissive' not in selinux_status_before.stdout"
      notify:
        - Verify SELinux mode after change

    - name: Ensure SELinux is set to permissive on boot
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=permissive'
        backup: yes

#    - name: Verify SELinux status after change
#      command: sestatus
#      register: selinux_status_after
#      changed_when: false
#      failed_when: false
#
#    - name: Print SELinux status after change
#      debug:
#        msg: "After change, SELinux status: {{ selinux_status_after.stdout }}"
#
  handlers:
    - name: Verify SELinux mode after change
      command: sestatus
      register: selinux_status_check
      changed_when: false
      failed_when: false
      debug:
        msg: "SELinux mode after change is {{ selinux_status_check.stdout }}"

