---
- name: Setup Cloudera Manager and Dependencies
  hosts: cloudera_manager
  become: yes
  vars:
    cm_version: "7.11.3.28"
    cm_numeric_version: "60766845"
    cdh_version: "7.1.9.1023"
    cdh_numeric_version: "60818430"
    spark_version: "3.3.7191000.4"
    spark_numeric_version: "60728639"
    os_version: "redhat9"
    public_ip: "{{ ansible_default_ipv4.address }}"
    username: "<username>"
    password: "<password>"
  tasks:
    - name: Set dynamic variables
      set_fact:
        cdh7: "cdh{{ cdh_version.split('.')[0] }}"
        spark3: "spark{{ spark_version.split('.')[0] }}"
    
    - name: Create necessary directories
      file:
        path: "/var/www/html/cloudera-repos/{{ item }}"
        state: directory
      loop:
        - cloudera-manager
        - "{{ cdh7 }}/{{ cdh_version }}"
        - "spark3/{{ spark_version }}"
    
    - name: Download Cloudera Manager repo files
      get_url:
        url: "https://{{ username }}:{{ password }}@archive.cloudera.com/p/cm7/{{ cm_version }}/{{ os_version }}/yum/{{ item }}"
        dest: "/var/www/html/cloudera-repos/cloudera-manager/{{ item }}"
      loop:
        - cloudera-manager.repo
        - cloudera-manager-trial.repo
        - RPM-GPG-KEY-cloudera
        - allkeys.asc
        - allkeyssha256.asc
    
    - name: Configure Cloudera Manager repo
      template:
        src: cloudera-manager.repo.j2
        dest: /etc/yum.repos.d/cloudera-manager.repo
    
    - name: Configure PostgreSQL repo
      template:
        src: postgresql.repo.j2
        dest: /etc/yum.repos.d/postgresql.repo
    
    - name: Download Cloudera Manager RPMs
      get_url:
        url: "https://{{ username }}:{{ password }}@archive.cloudera.com/p/cm7/{{ cm_version }}/{{ os_version }}/yum/RPMS/x86_64/{{ item }}"
        dest: "/var/www/html/cloudera-repos/cloudera-manager/cm{{ cm_version }}/{{ os_version }}/yum/RPMS/x86_64/"
      loop:
        - "cloudera-manager-agent-{{ cm_version }}-{{ cm_numeric_version }}.el9.x86_64.rpm"
        - "cloudera-manager-daemons-{{ cm_version }}-{{ cm_numeric_version }}.el9.x86_64.rpm"
        - "cloudera-manager-server-{{ cm_version }}-{{ cm_numeric_version }}.el9.x86_64.rpm"
        - "cloudera-manager-server-db-2-{{ cm_version }}-{{ cm_numeric_version }}.el9.x86_64.rpm"
    
    - name: Download CDH Parcels
      get_url:
        url: "https://{{ username }}:{{ password }}@archive.cloudera.com/p/{{ cdh7 }}/{{ cdh_version }}/parcels/CDH-{{ cdh_version }}-1.{{ cdh7 }}.p{{ cdh_numeric_version }}-el9.parcel"
        dest: "/var/www/html/cloudera-repos/{{ cdh7 }}/{{ cdh_version }}/parcels/"
    
    - name: Download Spark Parcels
      get_url:
        url: "https://{{ username }}:{{ password }}@archive.cloudera.com/p/{{ spark3 }}/{{ spark_version }}/parcels/SPARK3-{{ spark_version }}-1-1.p0.{{ spark_numeric_version }}-el9.parcel"
        dest: "/var/www/html/cloudera-repos/{{ spark3 }}/{{ spark_version }}/parcels/"
    
    - name: Run createrepo
      command: "createrepo --baseurl http://{{ public_ip }}/cloudera-repos/cloudera-manager/ /var/www/html/cloudera-repos/cloudera-manager/"
      args:
        chdir: /var/www/html/cloudera-repos/cloudera-manager/
    
    - name: Ensure services are started
      service:
        name: httpd
        state: started
        enabled: yes
