- name: Enroll nodes as IPA clients
  hosts: all:!ipaserver
  become: true
  vars_files:
    - group_vars/all.yml

  tasks:
    - name: Check if IPA client is already installed
      command: ipa-client-install --version
      register: ipa_client_check
      changed_when: false
      ignore_errors: true  # Avoid failure if IPA is not installed

    - name: Derive BaseDN from ipaserver_domain
      set_fact:
        basedn: "{{ ipaserver_domain.split('.') | map('regex_replace', '^(.*)$', 'dc=\\1') | join(',') }}"

    - name: Debug inventory hostname
      debug:
        msg: "This host is {{ inventory_hostname }}"

    - name: Join IPA in force mode with maximum 5 kinit attempts
      freeipa.ansible_freeipa.ipaclient_join:
        servers: ["ipaserver.{{ ipaserver_domain }}"]
        realm: "{{ ipaserver_realm }}"
        basedn: "{{ basedn }}"
        hostname: "{{ inventory_hostname }}"
        principal: "{{ ipaadmin_principal }}"
        password: "{{ ipaadmin_password }}"
        force_join: yes
        kinit_attempts: 5
        krb_name: "/tmp/tmpkrb5.conf"

    - name: Display installation result
      debug:
        var: ipa_client_install_result.stdout
      when: ipa_client_check.rc != 0  # Show output only when installation happens
