- name: Enroll nodes as IPA clients
  hosts: all:!ipaserver
  become: true
  vars_files:
    - group_vars/all.yml

  tasks:
    - name: Check if IPA client is installed
      ansible.builtin.command: ipa-client-install --version
      register: ipa_client_check
      changed_when: false
      ignore_errors: true

    - name: Print IPA client version if already installed
      debug:
        msg: "IPA Client is already installed. Version: {{ ipa_check.stdout }}"
      when: ipa_client_check.rc == 0

    # - name: Install required packages
    #   ansible.builtin.dnf:
    #     name: freeipa-client
    #     state: present
    #   when: ipa_check.rc != 0

    - name: Debug inventory hostname
      debug:
        msg: "This host is {{ inventory_hostname }}"

    - name: Run FreeIPA client installation (non-interactive)
      ansible.builtin.command: >
        ipa-client-install --unattended --force-join --force
        --realm={{ ipaserver_realm }} --domain={{ ipaserver_domain }} --server="{{ ansible_fqdn }}"
        --principal={{ ipaadmin_principal }} --password={{ ipaadmin_password }}
        --mkhomedir --enable-dns-updates --ntp-server=pool.ntp.org
      register: ipa_client_output
      changed_when: "'Client configuration complete' in ipa_client_output.stdout"
      when: ipa_client_check.rc != 0
      no_log: true  # Hide password from logs

    - name: Display IPA client installation output
      debug:
        msg: "{{ ipa_client_output.stdout_lines }}"
      when: ipa_client_check.rc != 0

    # - name: Join IPA in force mode with maximum 5 kinit attempts
    #   freeipa.ansible_freeipa.ipaclient_join:
    #     servers: ["ipaserver.{{ ipaserver_domain }}"]
    #     realm: "{{ ipaserver_realm }}"
    #     basedn: "{{ basedn }}"
    #     hostname: "{{ inventory_hostname }}"
    #     principal: "{{ ipaadmin_principal }}"
    #     password: "{{ ipaadmin_password }}"
    #     force_join: yes
    #     kinit_attempts: 5
    #     krb_name: "/tmp/tmpkrb5.conf"

