---
- name: Playbook to configure IPA server
  hosts: ipaserver
  become: true
  vars_files:
    - group_vars/all.yml

  tasks:
    - name: Install required packages
      dnf:
        name:
          - ipa-server
          - bind
          - bind-dyndb-ldap
          - ipa-server-dns
          - firewalld
        state: present

    - name: Set Java alternatives (if required)
      command: update-alternatives --config java
      register: java_result
      changed_when: "'selection' in java_result.stdout"

    - name: Extract NetBIOS name from realm
      set_fact:
        netbios_name: "{{ ipaserver_realm.split('.')[0] }}"

    - name: Run IPA server installation
      command: >
        ipa-server-install --setup-dns
        --hostname={{ ipaserver_hostname }}
        --domain={{ ipaserver_domain }}
        --realm={{ ipaserver_realm }}
        --ds-password={{ ipadm_password }}
        --admin-password={{ ipa_admin_password }}
        --no-dnssec-validation
        --netbios-name={{ netbios_name }}
        {% if dns_forwarders == 'no' %} --no-forwarders {% endif %}
        {% if reverse_zones == 'no' %} --no-reverse {% endif %}
        {% if chrony_enabled == 'yes' %} --ntp {% endif %}
      register: ipa_install_result
      changed_when: "'The ipa-server-install command was successful' in ipa_install_result.stdout"

    - name: Display derived NetBIOS name (for verification)
      debug:
        msg: "Derived NetBIOS Name: {{ netbios_name }}"
