- hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: "{{ lookup('env', 'ANSIBLE_PYTHON_INTERPRETER') }}"

  tasks:
    - name: Ensure Python interpreter is correct
      debug:
        msg: "Using Python interpreter {{ ansible_python_interpreter }}"

    - name: Get Python version
      command: "{{ ansible_python_interpreter }} --version"
      register: python_version

    - name: Display Python version
      debug:
        msg: "Python version is: {{ python_version.stdout }}"

