- name: Generate sim.conf for Cloudera Manager
  template:
    src: sim.conf.j2
    dest: "/etc/cloudera-scm-server/sim.conf"
    owner: cloudera-scm
    group: cloudera-scm
    mode: "0644"

- name: Restart Cloudera Manager
  service:
    name: cloudera-scm-server
    state: restarted
